[package]
name = "rodep"
version = "0.1.0"
authors = ["AmaranthineCodices <AmaranthineCodices@gmail.com>"]

[dependencies]
clap = "~2.31.2"
git2 = "0.7.1"
url = "1.7.0"
regex = "0.2.10"
lazy_static = "1.0.0"